name: Lean Action CI

on:
  pull_request:
    paths:
      - "analysis/markov/**"
      - "post-cip/formal-crypto/lean/**"
  push:
    branches:
      - main
    paths:
      - "analysis/markov/**"
      - "post-cip/formal-crypto/lean/**"

jobs:
  - name: Markov simulator
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1
        with:
          lake-package-directory: analysis/markov
          use-github-cache: true
  - name: Formal spec for sortition, voting, certificates
    if: true
    runs-on: ubuntu-latest
    steps:
      - name: Install Elan
        run: |
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
      - name: Build ProofWidgets
        run: |
          npm --version
          cd post-cip/formal-crypto/lean
          lake update
          cd .lake/packages/proofwidgets
          lake build
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1
        with:
          lake-package-directory: post-cip/formal-crypto/lean
          use-github-cache: true
