name: Leios Crypto Spec Action CI

on:
  pull_request:
    paths:
      - "post-cip/formal-crypto/lean/**"
  push:
    branches:
      - main
    paths:
      - "post-cip/formal-crypto/lean/**"

jobs:
  - name: Install ProofWidgets NPM dependencies
    run: |
      cd .lake/packages/proofwidgets/widget
      npm clean-install
  - name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1
        with:
          lake-package-directory: "post-cip/formal-crypto/lean"
          use-github-cache: true
